### PR TITLE
chore(*): check in updated node_modules dir per current package.json

### PR DESCRIPTION
**Pull request by vdice**
This checks in the updated node_modules dir using the current dep versions in package.json.  (I just ran `npm install` from the current head commit/main branch.)

The recent [v0.1.2](https://github.com/getporter/gh-action/releases/tag/v0.1.2) release was _intended_ to pull in recent dep bumps, but their changes weren't actually included in the node_modules dir that we track here.

We should cut a new patch release once this is merged.  When released, this should address https://github.com/getporter/gh-action/issues/14

### CODE REVIEW

**Comment by vdice** [comment]
@radu-matei could you take a look at this if/when you have a spare moment?

**Comment by radu-matei** [comment]
In other GitHub Actions that I maintain, the `main` branch has the `node_modules` directory in `.gitignore`, and only the release branches contain it.

This has the advantage of keeping a clean main branch, but has the additional burden of updating the release branches accordingly.

If the commit updates the internal Actions packages, then #14 should be solved, and my comment does not block this PR.

**Comment by carolynvs** [comment]
@vdice What can we do to get #14 fixed? I'm unclear on why it's related to this, and which relies upon which. 😀

**Review by carolynvs — APPROVED** [review]
LGTM, I'm fine with continuing to have node_modules checked into the main branch.

**Pull request merged**
